import fs from 'node:fs';
import path from 'node:path';
import { ROOT, readJson, repoPath } from './lib/validation.mjs';

export const DEFAULT_OUTPUT = '_site';
const ALLOWED_OUTPUTS = new Set([DEFAULT_OUTPUT]);

function copyEntry(source, destination) {
  const stat = fs.lstatSync(source);
  if (stat.isSymbolicLink()) throw new Error(`deployment input must not be a symbolic link: ${source}`);
  if (stat.isDirectory()) {
    fs.mkdirSync(destination, { recursive: true });
    for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
      copyEntry(path.join(source, entry.name), path.join(destination, entry.name));
    }
    return;
  }
  if (!stat.isFile()) throw new Error(`unsupported deployment input: ${source}`);
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.copyFileSync(source, destination, fs.constants.COPYFILE_EXCL);
}

function walkRelative(directory, prefix = '') {
  const files = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) files.push(...walkRelative(path.join(directory, entry.name), relative));
    else files.push(relative);
  }
  return files;
}

export function preparePages(root = ROOT, outputRelative = DEFAULT_OUTPUT) {
  const state = readJson(root, 'config/project-state.json');
  if (!ALLOWED_OUTPUTS.has(outputRelative)) {
    throw new Error(`deployment output must be the dedicated ${DEFAULT_OUTPUT}/ directory`);
  }
  const output = repoPath(root, outputRelative);
  if (state.deployment.artifactPaths.some((entry) => output === repoPath(root, entry))) {
    throw new Error('deployment output must not overlap an artifact source');
  }
  const marker = repoPath(root, '_site.moguria-generated');
  const markerValid = fs.existsSync(marker) && fs.lstatSync(marker).isFile() && fs.readFileSync(marker, 'utf8') === 'generated by scripts/prepare-pages.mjs\n';
  if (fs.existsSync(output)) {
    const outputStat = fs.lstatSync(output);
    if (!markerValid || !outputStat.isDirectory() || outputStat.isSymbolicLink()) {
      throw new Error(`refusing to replace unmarked or unsafe output: ${output}`);
    }
  }
  if (fs.existsSync(output)) fs.rmSync(output, { recursive: true });
  fs.mkdirSync(output, { recursive: true });
  fs.writeFileSync(marker, 'generated by scripts/prepare-pages.mjs\n');
  for (const relative of state.deployment.artifactPaths || []) {
    copyEntry(repoPath(root, relative), path.join(output, relative));
  }
  const files = walkRelative(output).sort();
  return { output, files };
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname)) {
  const result = preparePages(ROOT, DEFAULT_OUTPUT);
  console.log(`Prepared ${result.files.length} static file(s) in ${path.relative(ROOT, result.output)}/.`);
}
